[primary]
background = '#e1e2e7'
foreground = '#3760bf'
[normal]
black =   '#e9e9ed'
red =     '#f52a65'
green =   '#587539'
yellow =  '#8c6c3e'
blue =    '#2e7de9'
magenta = '#9854f1'
cyan =    '#007197'
white =   '#6172b0'
[bright]
black =   '#a1a6c5'
red =     '#f52a65'
green =   '#587539'
yellow =  '#8c6c3e'
blue =    '#2e7de9'
magenta = '#9854f1'
cyan =    '#007197'
white =   '#3760bf'
[[indexed_colors]]
index = 16
color = '#b15c00'
[[indexed_colors]]
index = 17
color = '#c64343'

