#!/bin/sh
xsetroot -cursor_name left_ptr
pkill sxhkd
sxhkd -c ${HOME}/.config/bspwm/sxhkdrc &
pkill picom
while pgrep -x picom >/dev/null; do sleep 1; done
picom &
pkill dunst
dunst &
feh --bg-fill ${HOME}/system/wallpapers/default.jpg &
${HOME}/.config/polybar/launch.sh

source ${HOME}/.config/bspwm/scripts/bspwm_dimensions.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width          02
bspc config normal_border_color   '#2e3440'
bspc config active_border_color   '#4e586d'
bspc config focused_border_color  '#8894aa'
bspc config window_gap            10
bspc config top_padding           $((POLYBAR_HEIGHT+10))
bspc config bottom_padding        04
bspc config left_padding          04
bspc config right_padding         04

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        true
bspc config focus_follows_pointer true
bspc config honor_size_hints      true
bspc config ignore_ewmh_focus     true

# clean rules list to avoid duplicate on config reload
bspc rule -r \*:\*

if [[ $(hostname) == 'swimmer' ]]; then
  bspc rule -a \*                 state=pseudo_tiled
else
  bspc rule -a \*                 state=tiled
fi
bspc rule -a \*:\*:sys            desktop='^1'
bspc rule -a \*:\*:work           desktop='^2'
if [[ $(hostname) == 'swimmer' ]]; then
  bspc rule -a \*:\*:com          desktop='^3' state=floating
else
  bspc rule -a \*:\*:com          desktop='^3'
fi
bspc rule -a \*:\*:tj             desktop='^3'
bspc rule -a \*:\*:komala         desktop='^5'
bspc rule -a \*:\*:tj-laptop      desktop='^6'
bspc rule -a \*:\*:home           desktop='^6'
bspc rule -a \*:\*:swimmer        desktop='^6'
bspc rule -a scribus              desktop='^7'
bspc rule -a Thunderbird          desktop='^7'
bspc rule -a Darktable            desktop='^8'
bspc rule -a Gimp                 desktop='^8'
bspc rule -a Inkscape             desktop='^8'
bspc rule -a Audacity             desktop='^9'
bspc rule -a puddletag            desktop='^9'
bspc rule -a Gvim                 state=floating center=on
bspc rule -a Lxappearance         state=floating center=on rectangle=${newwidth}x${newheight}+${hor}+${ver}

bspc config external_rules_command ${HOME}/.config/bspwm/scripts/external_rules.sh
