#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4
Alt=Mod1

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close_and_remove
hc keybind $Mod-Return spawn "${TERMINAL:-uxterm}"

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-$Alt-h focus left
hc keybind $Mod-$Alt-j focus down
hc keybind $Mod-$Alt-k focus up
hc keybind $Mod-$Alt-l focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# splitting frames
hc keybind $Mod-Control-a split auto
hc keybind $Mod-Control-b chain , split vertical 0.5 \
  , focus down --level=frame \
  , set_attr tags.focus.tiling.focused_frame.algorithm grid
hc keybind $Mod-Control-r chain , split horizontal 0.5 \
  , focus right --level=frame \
  , set_attr tags.focus.tiling.focused_frame.algorithm grid
hc keybind $Mod-Control-space split explode
# remove frame
hc keybind $Mod-Control-x remove

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h resize left +$resizestep
hc keybind $Mod-Control-j resize down +$resizestep
hc keybind $Mod-Control-k resize up +$resizestep
hc keybind $Mod-Control-l resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
  hc add "${tag_names[$i]}"
  key="${tag_keys[$i]}"
  if [ -n "$key" ] ; then
    hc keybind "$Mod-$key" use_index "$i"
    hc keybind "$Mod-Shift-$key" move_index "$i"
  fi
done

if [ $HOSTNAME = 'swimmer' ]; then
  hc floating 3 on
fi

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma use_index -1 --skip-visible
hc keybind $Mod-Escape use_previous

# layouting
hc keybind $Mod-$Alt-f set_attr tags.focus.floating toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-p set_attr clients.focus.pseudotile toggle
hc keybind $Mod-Shift-x spawn $HOME/.config/herbstluftwm/scripts/maximize.sh
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-space cycle_layout +1 max grid

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-Tab cycle_all +1
hc keybind $Mod-Shift-Tab cycle_all -1
hc keybind $Mod-$Alt-u jumpto urgent

# theme
width=4
gap=$((width*3))
color_fg=$(xrdb -query | grep 'foreground' | awk '{print $2}')
color_bg=$(xrdb -query | grep 'background' | awk '{print $2}')
color_red=$(xrdb -query | grep 'color1:' | awk '{print $2}')
color_green=$(xrdb -query | grep 'color2:' | awk '{print $2}')
color_blue=$(xrdb -query | grep 'color4:' | awk '{print $2}')
color_cyan=$(xrdb -query | grep 'color6:' | awk '{print $2}')
if [ $(cat $HOME/.config/colours/background) = 'dark' ]; then
  op='ee'
  tr='11'
else
  op='aa'
  tr='33'
fi
color_active="$color_fg$op"
color_normal="$color_fg$tr"

hc set_layout grid

hc attr theme.title_when multiple_tabs
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc attr theme.border_width "$width"
hc attr theme.active.color "$color_green$op"
hc attr theme.normal.color "$color_normal"
hc attr theme.urgent.color "$color_red"

hc attr settings.focus_follows_mouse true
hc attr settings.focus_stealing_prevention true

hc attr settings.default_frame_layout grid
hc attr settings.smart_frame_surroundings hide_all
hc attr settings.always_show_frame false
hc attr settings.frame_border_width "$gap"
hc attr settings.frame_transparent_width 0
hc attr settings.frame_bg_transparent true
hc attr settings.frame_gap "$gap"
hc attr settings.frame_padding 0
hc attr settings.frame_border_active_color "$color_green$op"
hc attr settings.frame_active_opacity 0
hc attr settings.frame_border_normal_color "$color_normal"
hc attr settings.frame_normal_opacity 50

hc attr settings.tabbed_max true
hc attr settings.smart_window_surroundings true
hc attr settings.gapless_grid true
hc attr settings.window_gap "$gap"

hc pad 0 $((POLYBAR_HEIGHT+10)) 0 0 0

# rules
hc unrule -F
hc rule focus=on
hc rule floatplacement=smart
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on
hc rule instance=sys tag=1
hc rule instance=work tag=2
hc rule instance=com tag=3 floating=on
hc rule instance=tj tag=3
hc rule instance=komala tag=5
hc rule instance=home tag=6
hc rule instance=tj-laptop tag=6
hc rule class=Calculator floating=on
hc rule class=Explore floating=on
hc rule class=Keybindings floating=on
hc rule class=MC floating=on
hc rule class=Music floating=on
hc rule class=Explore floating=on
hc rule class=Scratchpad floating=on
hc rule class=Sysinfo floating=on
hc rule class=Calendar floating=on
hc rule class~'[Gg]pick' floating=on
hc rule class~'[Ll]xappearance' floating=on
hc rule class=scribus tag=7
hc rule class=Thunderbird tag=7
hc rule class=Thunderbird title='Edit Item' floating=on tag=7
hc rule class=Darktable tag=8
hc rule class=Gimp tag=8
hc rule class=Inkscape tag=8
hc rule class=Audacity tag=9
hc rule class=puddletag tag=9

hc apply_rules --all

hc set tree_style '╾│ ├└╼─┐'

hc unlock

pkill sxhkd
sxhkd -c $HOME/.config/herbstluftwm/sxhkdrc &
pkill picom
while pgrep -x picom >/dev/null; do sleep 1; done
#/usr/local/src/Tools/x11/picom-yshui.git/build/src/picom --config $HOME/.config/picom/herbstluftwm.conf &
/usr/local/src/Tools/x11/picom-ibhagwan.git/build/src/picom --experimental-backends --config $HOME/.config/picom/herbstluftwm.conf &
pkill dunst
dunst &
if [ $HOSTNAME = 'swimmer' ]; then
  feh --conversion-timeout 1 --image-bg $color_bg --bg-max --geometry '+1900' $HOME/system/wallpapers/gecko.svg &
elif [ $HOSTNAME = 'tj' ]; then
  feh --conversion-timeout 4 --image-bg $color_bg --bg-max --geometry '+900' $HOME/system/wallpapers/gecko.svg &
fi
$HOME/.config/polybar/launch.sh
