#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4
Alt=Mod1

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn "${TERMINAL:-uxterm}"

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-$Alt-h focus left
hc keybind $Mod-$Alt-j focus down
hc keybind $Mod-$Alt-k focus up
hc keybind $Mod-$Alt-l focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# splitting frames
hc keybind $Mod-Control-a split auto
hc keybind $Mod-Control-u split bottom 0.5
hc keybind $Mod-Control-o split right 0.5
hc keybind $Mod-Control-space split explode
# remove frame
hc keybind $Mod-Control-r remove

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h resize left +$resizestep
hc keybind $Mod-Control-j resize down +$resizestep
hc keybind $Mod-Control-k resize up +$resizestep
hc keybind $Mod-Control-l resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma use_index -1 --skip-visible
hc keybind $Mod-Escape use_previous

# layouting
hc keybind $Mod-$Alt-p pseudotile toggle
hc keybind $Mod-$Alt-s floating toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-$Alt-f spawn $HOME/.config/herbstluftwm/scripts/maximize.sh
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-Tab cycle_all +1
hc keybind $Mod-Shift-Tab cycle_all -1
hc keybind $Mod-$Alt-u jumpto urgent

# theme
width=4
gap=14
color_base=$(xrdb -query | grep 'foreground' | awk '{print $2}')
if [ $(cat $HOME/.config/colours/background) = 'dark' ]; then
  op='ee'
  tr='11'
else
  op='aa'
  tr='33'
fi
color_active="$color_base$op"
color_normal="$color_base$tr"
color_red=$(xrdb -query | grep 'color1:' | awk '{print $2}')
color_green=$(xrdb -query | grep 'color2:' | awk '{print $2}')
color_blue=$(xrdb -query | grep 'color4:' | awk '{print $2}')
color_cyan=$(xrdb -query | grep 'color6:' | awk '{print $2}')

hc set_layout horizontal

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc attr theme.border_width "$width"
hc attr theme.active.color "$color_green$op"
hc attr theme.normal.color "$color_normal"
hc attr theme.urgent.color "$color_red"

hc attr settings.focus_follows_mouse true
hc attr settings.focus_stealing_prevention true

hc attr settings.default_frame_layout horizontal
hc attr settings.smart_frame_surroundings hide_all
hc attr settings.always_show_frame false
hc attr settings.tabbed_max true
hc attr settings.frame_border_width "$gap"
hc attr settings.frame_transparent_width 0
hc attr settings.frame_bg_transparent true
hc attr settings.frame_gap "$gap"
hc attr settings.frame_padding 0
hc attr settings.frame_border_active_color "$color_green$op"
hc attr settings.frame_active_opacity 0
hc attr settings.frame_border_normal_color "$color_normal"
hc attr settings.frame_normal_opacity 50

hc attr settings.smart_window_surroundings true
hc attr settings.gapless_grid true
hc attr settings.window_gap "$gap"

hc pad 0 $((POLYBAR_HEIGHT+5)) 0 0 0

# rules
hc unrule -F
hc rule focus=on
hc rule floatplacement=smart
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on
hc rule instance=sys tag=1
hc rule instance=work tag=2
hc rule instance=com tag=3 floating=on
hc rule instance=tj tag=3
hc rule instance=komala tag=5
hc rule instance=home tag=6
hc rule instance=tj-laptop tag=6
hc rule title=Calculator floating=on
hc rule title=Explore floating=on
hc rule title=Keybindings floating=on
hc rule title=Ranger floating=on
hc rule title=Scratchpad floating=on
hc rule title=Sysinfo floating=on
hc rule title=Calendar floating=on
hc rule class~'[Gg]color2' floating=on
hc rule class~'[Ll]xappearance' floating=on
hc rule class=scribus tag=7
hc rule class=Thunderbird tag=7
hc rule class=Thunderbird title='Edit Item' floating=on tag=7
hc rule class=Darktable tag=8
hc rule class=Gimp tag=8
hc rule class=Inkscape tag=8
hc rule class=Audacity tag=9
hc rule class=puddletag tag=9

hc apply_rules --all

hc set tree_style '╾│ ├└╼─┐'

hc unlock

pkill sxhkd
sxhkd -c $HOME/.config/herbstluftwm/sxhkdrc &
pkill picom
while pgrep -x picom >/dev/null; do sleep 1; done
# /usr/local/src/Tools/x11/yshui-picom.git/build/src/picom --experimental-backends --vsync --config $HOME/.config/picom/yshui-picom.conf &
/usr/local/src/Tools/x11/ibhagwan-picom.git/build/src/picom --experimental-backends --vsync --config $HOME/.config/picom/ibhagwan-picom.conf &
pkill dunst
dunst &
feh --bg-fill $HOME/system/wallpapers/default.jpg &
$HOME/.config/polybar/launch.sh
